/*
 * generated by Xtext
 */
package de.emueller.xtext.recordmapper.validation

import de.emueller.xtext.recordmapper.recordMapper.Field
import de.emueller.xtext.recordmapper.recordMapper.RecordMapperPackage
import java.util.List
import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class RecordMapperValidator extends AbstractRecordMapperValidator {

//  public static val INVALID_NAME = 'invalidName'
//
	@Check
	def checkRequiredFiels(Object mongoRecord) {
		
	}
	
	def hasField(List<Field> fields, String fieldname) {
		for (field : fields) {
			if (field.name == fieldname) {
				return true
			}
		}
		return false
	}
	
}
