/*
 * generated by Xtext
 */
package de.emueller.xtext.recordmapper.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.emueller.xtext.recordmapper.ui.internal.RecordMapperActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RecordMapperExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RecordMapperActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RecordMapperActivator.getInstance().getInjector(RecordMapperActivator.DE_EMUELLER_XTEXT_RECORDMAPPER_RECORDMAPPER);
	}
	
}
