/*
* generated by Xtext
*/
package de.emueller.xtext.recordmapper.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RecordMapperAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/emueller/xtext/recordmapper/parser/antlr/internal/InternalRecordMapper.tokens");
	}
}
