/*
* generated by Xtext
*/
package de.emueller.xtext.recordmapper.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.emueller.xtext.recordmapper.services.RecordMapperGrammarAccess;

public class RecordMapperParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RecordMapperGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.emueller.xtext.recordmapper.parser.antlr.internal.InternalRecordMapperParser createParser(XtextTokenStream stream) {
		return new de.emueller.xtext.recordmapper.parser.antlr.internal.InternalRecordMapperParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RecordMappperFile";
	}
	
	public RecordMapperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RecordMapperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
