/*
* generated by Xtext
*/
package de.emueller.xtext.recordmapper;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RecordMapperUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.emueller.xtext.recordmapper.ui.internal.RecordMapperActivator.getInstance().getInjector("de.emueller.xtext.recordmapper.RecordMapper");
	}
	
}
