/*
 * generated by Xtext
 */
package de.emueller.xtext.recordmapper.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RecordMapperUiModule extends de.emueller.xtext.recordmapper.ui.AbstractRecordMapperUiModule {
	public RecordMapperUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
