/*
 * generated by Xtext
 */
package de.emueller.xtext.recordmapper;

import org.eclipse.xtext.generator.IGenerator;

import de.emueller.xtext.recordmapper.generator.RecordMapperGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RecordMapperRuntimeModule extends de.emueller.xtext.recordmapper.AbstractRecordMapperRuntimeModule {

	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return RecordMapperGenerator.class;
	}
}
