/*
 * generated by Xtext
 */
package de.emueller.xtext.recordmapper.ui.contentassist

import de.emueller.xtext.recordmapper.ui.contentassist.AbstractRecordMapperProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class RecordMapperProposalProvider extends AbstractRecordMapperProposalProvider {
}
